### ISSUE TITLE
move players ready status to Clan Tag

### ISSUE THREAD

**Issue by burnSTATION** [burnSTATION/spgt#9]
easily done with Player.clan_tag

we could make their clan tags [READY] and [NOT READY]

**Comment by burnSTATION** [comment]
Not possible with current SP version

**Comment by burnSTATION** [comment]
Not possible with current SP version

**Comment by timorthi** [comment]
@burnSTATION There's still a solution to this - although more intrusive UI-wise - we can have a persistent menu that displays the ready status of the players. It can list both ready/not ready players or just one of them (I'm thinking of just showing the not ready players). This way we won't have to depend on clan_tag offsets. What do you think?

**Comment by timorthi** [comment]
On top of that we can also have a `TickRepeat` instance ([docs](http://wiki.sourcepython.com/_modules/listeners/tick.html)) that posts something via `SayText` every minute or so that says something along the lines of "Waiting for player1, player2 to ready up..." so players have the option to keep the ready status menu closed
